import { readFile, writeFile } from "node:fs/promises";

const sourceDirectory = new URL("../src/experiment/", import.meta.url);
const model = await readFile(new URL("model.js", sourceDirectory), "utf8");
const app = await readFile(new URL("app.js", sourceDirectory), "utf8");
const importLine = /^import \{ DEFAULTS, runExperiment \} from "\.\/model\.js";\r?\n/m;
if (!importLine.test(app)) throw new Error("Unexpected app import; update the browser build script");
const bundled = `// Generated by npm run build:browser. Edit model.js and app.js instead.\n(() => {\n"use strict";\n${model.replace(/^export /gm, "")}\n${app.replace(importLine, "")}\n})();\n`;
await writeFile(new URL("standalone.js", sourceDirectory), bundled);
console.log("Built src/experiment/standalone.js for direct file:// opening");
